POST http://localhost:3333/tweets HTTP/1.1
content-type: application/json
Authorization: 2b5234e7-a6a1-46e3-af31-d8ac47154f6a

# {
# "content": "Adorei os recursos dessa plataforma"
# }

# {
# "content": "Muito massa essa rede social nova"
# }


# {
# "content": "Oi Henrique. Legal te encontrar aqui na rede. Me adiciona ai. Valeu"
# }

# {
# "content": "Oi Paula. Legal te ver aqui na rede. Me adiciona ai. Valeu"
# }

# {
# "content": "Sabado de sol. Passeando com a nega no poise. #sabadou"
# }
