POST http://localhost:3333/tweets HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxNGMwLTUxOWEtNDBmMy1iMzFkLWE4ODhkYTc3N2U5OCIsIm5hbWUiOiJFc3RlZmFuaSBTYW50b3MiLCJ1c2VybmFtZSI6ImVzdGVmLnNhbnRvcyIsImF2YXRhciI6IjFhNWNiNzZjLTc3NDctNDI0YS05MGRkLTZiY2JjMjNmOGI5YiIsImVtYWlsIjoiZXN0ZWZpbmhhQGdtYWlsLmNvbSIsImlhdCI6MTcwNDkwOTc3MSwiZXhwIjoxNzA0OTM4NTcxfQ.LxWwmcDYP--0HMOLavb88b3ODRkiW1gex7wuahdditw

# {
# "content": "Também achei top essa nova rede social"
# }

# {
# "content": "Oi Gustavo qu legal te encontrar aqui na rede. Me add ai. Valeu"
# }


{
"content": "Adorei os recursos dessa plataforma"
}


# {
# "content": "Final de semana promete..."
# }


# {
# "content": "Oi Henrique. Legal te encontrar aqui na rede. Me adiciona ai. Valeu"
# }

# {
# "content": "Oi Paula. Legal te ver aqui na rede também. Me adiciona ai. Valeu"
# }

# {
# "content": "Sabado de sol. Passeando com a nega no poise. #sabadou"
# }

# {
# "content": "Curtindo o final de semana com uma cervejinha"
# }

