GET http://localhost:3333/tweets/ HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNjg5MzI1LTkzODgtNDQ2YS1iOTdmLTJlZDY2NTlhNjQ4MCIsIm5hbWUiOiJSYWZhZWwgU291emEiLCJ1c2VybmFtZSI6InJhZmEuc291emEiLCJhdmF0YXIiOiJiMGQ2NGQ5Yi1mOGM0LTRiZDYtYTM4NC04NzhmM2Y3NDJkZjAiLCJlbWFpbCI6InJmc291emFAZ21haWwuY29tIiwiaWF0IjoxNzA0OTQxNTQzLCJleHAiOjE3MDQ5NzAzNDN9.FvSKfqU5cFg43fU7rnxdwFWpqMbL9kLM0bElSWOhuTU