GET http://localhost:3333/tweets/d73c7f8c-0ca3-44e7-87b7-dd59c92346e7 HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NjFhNTM2LWU5NGUtNGZhYy05NDllLWE1NDUyYWRiMWQzOSIsIm5hbWUiOiJBbGV4IE1lbmRlcyIsInVzZXJuYW1lIjoiYWxleC5tZW5kZXMiLCJhdmF0YXIiOiI5YzQ2NWIxOC0zODIxLTRkZmEtYmI0NC0xNDA3ODMzYzVhMWMiLCJlbWFpbCI6ImFsZU1lbmRlc0BnbWFpbC5jb20iLCJpYXQiOjE3MDUxNjEwNjUsImV4cCI6MTcwNTE4OTg2NX0.B87zzrok5DNUoNseWfBkcVvy-67p-cWzsBHrUgRdKng