GET http://localhost:3333/tweets/ HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyYmQ4ZmE3LTg5OWMtNDFhOS05MWNjLThjMmMzMDc3MGRmNSIsIm5hbWUiOiJNYXljb24gQW5kcmFkZSIsInVzZXJuYW1lIjoibWF5Y29uLmFuZHJhZGUiLCJhdmF0YXIiOiI5NGE4N2JjYS0xYzlmLTQ2YjQtODc2My1jYTE0ZWVhZDhiNTQiLCJlbWFpbCI6Im0uYW5kcmFkZUBnbWFpbC5jb20iLCJpYXQiOjE3MDYxODU4MDAsImV4cCI6MTcwNjIxNDYwMH0.VilnIy_isPPfkrPFYZATIyFq0XRGa3YnRfoLFFPiJ1Q