PUT http://localhost:3333/tweets/7e7a0fcf-5e8a-4f2c-b7cb-501f394b4e8d HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxNGMwLTUxOWEtNDBmMy1iMzFkLWE4ODhkYTc3N2U5OCIsIm5hbWUiOiJFc3RlZmFuaSBTYW50b3MiLCJ1c2VybmFtZSI6ImVzdGVmLnNhbnRvcyIsImF2YXRhciI6IjFhNWNiNzZjLTc3NDctNDI0YS05MGRkLTZiY2JjMjNmOGI5YiIsImVtYWlsIjoiZXN0ZWZpbmhhQGdtYWlsLmNvbSIsImlhdCI6MTcwNDk4MjU5OSwiZXhwIjoxNzA1MDExMzk5fQ.dNWXsv1GOOmXYKDaSN-3dna5VXvk0u72S7hzIp2VUqE

{
"content": "Essa plataforma é um máximo"
}




