PUT http://localhost:3333/tweets/c9fbd431-b0f7-4a93-8c73-3bd8ce8ccb37 HTTP/1.1
content-type: application/json
Authorization: 974cfaf0-928c-42cd-aca4-09d3d71a01b0

{
"content": "Oi Paulinha td bem amiga ?"
}




