POST http://localhost:3333/users HTTP/1.1
content-type: application/json

# {
# "name": "Gustavo Lima",
# "username": "guga@lima",
# "email":"glima@gmail.com",
# "password": "12345"
# }

# {
# "name": "Paula Campos Sales",
# "username": "p@sales.paxeco",
# "email":"pcampossales@gmail.com",
# "password": "12345"
# }

# {
# "name": "Marcia Paxeco",
# "username": "ma.paxeco",
# "email":"marcinha.paxeco@gmail.com",
# "password": "12345"
# }

# {
# "name": "Estefani Santos",
# "username": "estef.santos",
# "email":"estefinha@gmail.com",
# "password": "12345"
# }
