POST http://localhost:3000/users HTTP/1.1
content-type: application/json

# {
# "name":"Tatiane Pereira",
# "username":"tati.pereira.com",
# "email":"tatip@gmail.com",
# "password": "12345"
# }

# {
# "name": "Gustavo Lima",
# "username": "guga@lima",
# "email":"glima@gmail.com",
# "password": "12345"
# }

# {
# "name": "Cristian Alves",
# "username": "cris.alves",
# "email":"crisAlves@gmail.com",
# "password": "12345"
# }

# {
# "name": "Marcia Lima",
# "username": "ma.lima",
# "email":"marcinha@gmail.com",
# "password": "12345"
# }

{
"name": "Estefani Santos",
"username": "estef.santos",
"email":"estefinha@gmail.com",
"password": "12345"
}

# {
# "name": "Rafael Souza",
# "username": "rafa.souza",
# "email":"rfsouza@gmail.com",
# "password": "12345"  
# }

# {
# "name": "Bianca Silva",
# "username": "bianca",
# "email": "biSilva@gmail.com",
# "password": "12345"
# }

# {
# "name":"Alan Turing", 
# "username": "alan.turing",
# "email":"al.turing@gmail.com", 
# "password": "12345"
# }
