POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

# {
# "username": "rafa.souza",
# "password": "12345"
# }//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNjg5MzI1LTkzODgtNDQ2YS1iOTdmLTJlZDY2NTlhNjQ4MCIsIm5hbWUiOiJSYWZhZWwgU291emEiLCJ1c2VybmFtZSI6InJhZmEuc291emEiLCJhdmF0YXIiOiJiMGQ2NGQ5Yi1mOGM0LTRiZDYtYTM4NC04NzhmM2Y3NDJkZjAiLCJlbWFpbCI6InJmc291emFAZ21haWwuY29tIiwiaWF0IjoxNzA0OTQxNTQzLCJleHAiOjE3MDQ5NzAzNDN9.FvSKfqU5cFg43fU7rnxdwFWpqMbL9kLM0bElSWOhuTU

# {
# "username": "alex.mendes",
# "password": "12345"
# }
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NjFhNTM2LWU5NGUtNGZhYy05NDllLWE1NDUyYWRiMWQzOSIsIm5hbWUiOiJBbGV4IE1lbmRlcyIsInVzZXJuYW1lIjoiYWxleC5tZW5kZXMiLCJhdmF0YXIiOiI5YzQ2NWIxOC0zODIxLTRkZmEtYmI0NC0xNDA3ODMzYzVhMWMiLCJlbWFpbCI6ImFsZU1lbmRlc0BnbWFpbC5jb20iLCJpYXQiOjE3MDQ5MTMyODksImV4cCI6MTcwNDk0MjA4OX0.k6Me_xt190Q4o7C_ApSg70nkjM5bAIrhcZlaWjdrsSU

# {
# "username": "ma.lima",
# "password": "12345"
# }
//2cc06b63-1eac-4fed-93e9-a348143d9f0e

# {
# "username": "estef.santos",
# "password": "12345"
# }//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxNGMwLTUxOWEtNDBmMy1iMzFkLWE4ODhkYTc3N2U5OCIsIm5hbWUiOiJFc3RlZmFuaSBTYW50b3MiLCJ1c2VybmFtZSI6ImVzdGVmLnNhbnRvcyIsImF2YXRhciI6IjFhNWNiNzZjLTc3NDctNDI0YS05MGRkLTZiY2JjMjNmOGI5YiIsImVtYWlsIjoiZXN0ZWZpbmhhQGdtYWlsLmNvbSIsImlhdCI6MTcwNDk4MjU5OSwiZXhwIjoxNzA1MDExMzk5fQ.dNWXsv1GOOmXYKDaSN-3dna5VXvk0u72S7hzIp2VUqE


{
"username": "guga@lima",
"password": "12345"
}
//73fca808-cccb-4115-a827-37656b94f0fd

# {
# "username": "bianca",
# "password": "12345"
# }
//117113b7-b1bb-4e9f-af27-c684e2e69187

