POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

# {
# "username": "rafa.souza",
# "password": "12345"
# }

# {
# "username": "alex.mendes",
# "password": "12345"
# }
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NjFhNTM2LWU5NGUtNGZhYy05NDllLWE1NDUyYWRiMWQzOSIsIm5hbWUiOiJBbGV4IE1lbmRlcyIsInVzZXJuYW1lIjoiYWxleC5tZW5kZXMiLCJhdmF0YXIiOiI5YzQ2NWIxOC0zODIxLTRkZmEtYmI0NC0xNDA3ODMzYzVhMWMiLCJlbWFpbCI6ImFsZU1lbmRlc0BnbWFpbC5jb20iLCJpYXQiOjE3MDQ5MTMyODksImV4cCI6MTcwNDk0MjA4OX0.k6Me_xt190Q4o7C_ApSg70nkjM5bAIrhcZlaWjdrsSU

# {
# "username": "ma.lima",
# "password": "12345"
# }
//2cc06b63-1eac-4fed-93e9-a348143d9f0e

# {
# "username": "estef.santos",
# "password": "12345"
# }
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxNGMwLTUxOWEtNDBmMy1iMzFkLWE4ODhkYTc3N2U5OCIsIm5hbWUiOiJFc3RlZmFuaSBTYW50b3MiLCJ1c2VybmFtZSI6ImVzdGVmLnNhbnRvcyIsImF2YXRhciI6IjFhNWNiNzZjLTc3NDctNDI0YS05MGRkLTZiY2JjMjNmOGI5YiIsImVtYWlsIjoiZXN0ZWZpbmhhQGdtYWlsLmNvbSIsImlhdCI6MTcwNDkwOTc3MSwiZXhwIjoxNzA0OTM4NTcxfQ.LxWwmcDYP--0HMOLavb88b3ODRkiW1gex7wuahdditw

# {
# "username": "guga@lima",
# "password": "12345"
# }
//73fca808-cccb-4115-a827-37656b94f0fd

# {
# "username": "bianca",
# "password": "12345"
# }
//117113b7-b1bb-4e9f-af27-c684e2e69187

