POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

# {
# "name": "Paula Campos Sales",
# "username": "p@sales.paxeco",
# "email":"pcampossales@gmail.com",
# "password": "12345"
# }
//3e72367d-b4bc-4081-b3da-6f510f62204a

# {
# "name": "Henrique Gonçalves",
# "username": "hg@goncalves",
# "email":"hgonsalves@gmail.com",
# "password": "12345"
# }
//2b5234e7-a6a1-46e3-af31-d8ac47154f6a

# {
# "name": "Marcia Paxeco",
# "username": "ma.paxeco",
# "email":"marcinha.paxeco@gmail.com",
# "password": "12345"
# }
//147abc4d-77ea-4cd8-af4e-c540b79f7ffb

# {
# "name": "Estefani Santos",
# "username": "estef.santos",
# "email":"estefinha@gmail.com",
# "password": "12345"
# }
//f598ee1e-49a6-4d6d-95ad-550ab487375d