GET http://localhost:3333/auth/logout HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwY2JjODBmLWZhMjQtNDFiNC1hZDYyLWMwMmFjNGJkYTY5MSIsIm5hbWUiOiJSYWZhZWwgU291emEiLCJ1c2VybmFtZSI6InJhZmEuc291emEiLCJhdmF0YXIiOiI3YjdkOGRmYS1kYTVjLTRjMmUtODViOS1hMzU4M2ZhODc0NmQiLCJlbWFpbCI6InJmc291emFAZ21haWwuY29tIiwiaWF0IjoxNzAzNjQ4NjMyLCJleHAiOjE3MDM2Nzc0MzJ9.fvOJNRV1Jbwf93UQezd3kIag0ij0r3LAyXOIdUXJTvs