POST http://localhost:3333/reTweets HTTP/1.1
content-type: application/json
Authorization: b27c8dc2-79f2-4689-9b3e-5edc126381a1

{
"idTweetOriginal": "60dd87ba-729e-43b6-ac18-467f99e4e51f",
"contentReTweet": "Oi Paula. O que achou dessa nova rede social ?"
}


