POST http://localhost:3333/reTweets HTTP/1.1
content-type: application/json
Authorization: 2b5234e7-a6a1-46e3-af31-d8ac47154f6a

{
"idTweetOriginal": "8a8ad01c-ca44-4aaa-916a-a4dad71eb033",
"contentReTweet": "Oi Marcinha.Td bem ? como estão as coisas. Saudades. Te adicionei aqui"
}


