POST http://localhost:3333/reTweets HTTP/1.1
content-type: application/json
Authorization: 2257567e-ea8e-44b4-b6db-ebbe933bc2e1


{
"idTweetOriginal": "fa45a29e-fee8-4cb6-b8da-2002e9db67e1",
"contentReTweet": "Claro Guga. Já estavamos pensando em chamar vc "
}


