POST http://localhost:3000/likes/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTRiNzNiLTA2Y2UtNDZhZC1hY2E0LWFlYzgzYjMzN2U4OSIsIm5hbWUiOiJUYXRpYW5lIFBlcmVpcmEiLCJ1c2VybmFtZSI6InRhdGkucGVyZWlyYS5jb20iLCJhdmF0YXIiOiJlN2VlODExNy1jYjBlLTRhZTktYTNmOC0zMDk5ZDQxOTI3Y2QiLCJlbWFpbCI6InRhdGlwQGdtYWlsLmNvbSIsImlhdCI6MTcwNTU5MzgwMSwiZXhwIjoxNzA1NjIyNjAxfQ.jRnFH0uTyBJIGy8chYrwy6vSEhirR81sW7mLKME2mtI

{
    "idTweet" : "2cbd3742-2988-43f5-a58a-0126b0c99cc2"
}