POST http://localhost:3333/likes/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NjFhNTM2LWU5NGUtNGZhYy05NDllLWE1NDUyYWRiMWQzOSIsIm5hbWUiOiJBbGV4IE1lbmRlcyIsInVzZXJuYW1lIjoiYWxleC5tZW5kZXMiLCJhdmF0YXIiOiI5YzQ2NWIxOC0zODIxLTRkZmEtYmI0NC0xNDA3ODMzYzVhMWMiLCJlbWFpbCI6ImFsZU1lbmRlc0BnbWFpbC5jb20iLCJpYXQiOjE3MDUyNTczODcsImV4cCI6MTcwNTI4NjE4N30.1-DnP8XKiol01UWtzFfIjbh1ahcbkuFXzcCqWco_uE4

{
    "idTweet" : "d73c7f8c-0ca3-44e7-87b7-dd59c92346e4"
}