POST http://localhost:3333/follows/8cae47bd-48c3-495c-9d30-74ed3efb3bf1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5NzlhNTgxLTVlNmQtNDlhMy04MWEwLWVlMjhjMWMyYTVmOSIsIm5hbWUiOiJCaWFuY2EgU2lsdmEiLCJ1c2VybmFtZSI6ImJpYW5jYSIsImF2YXRhciI6ImJmYjg5YmY4LWExYmQtNGJmMi04Mzk0LWExYTk4MDlhYWJhZSIsImVtYWlsIjoiYmlTaWx2YUBnbWFpbC5jb20iLCJpYXQiOjE3MDUzMjUzNjIsImV4cCI6MTcwNTM1NDE2Mn0.h0eKTEA8SljXIQIEZLL3YnvY4CQRoYmqQegy5SXpIMQ

{
    "usernameFollowing":"bob.dilan"
}

# {
#     "usernameFollowing":"estef.santos"
# }

