GET http://localhost:3000/follows HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3NjFhNTM2LWU5NGUtNGZhYy05NDllLWE1NDUyYWRiMWQzOSIsIm5hbWUiOiJBbGV4IE1lbmRlcyIsInVzZXJuYW1lIjoiYWxleC5tZW5kZXMiLCJhdmF0YXIiOiI5YzQ2NWIxOC0zODIxLTRkZmEtYmI0NC0xNDA3ODMzYzVhMWMiLCJlbWFpbCI6ImFsZU1lbmRlc0BnbWFpbC5jb20iLCJpYXQiOjE3MDUyNTczODcsImV4cCI6MTcwNTI4NjE4N30.1-DnP8XKiol01UWtzFfIjbh1ahcbkuFXzcCqWco_uE4