DELETE  http://localhost:3333/follows/321b20a5-a0e0-41f3-badc-c86ad2b796f8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkN2JmMWI0LWFhMjItNGNhMy1hNDJkLTU5OTRkZTVlZTkyZiIsIm5hbWUiOiJHdXN0YXZvIExpbWEiLCJ1c2VybmFtZSI6Imd1Z2FAbGltYSIsImF2YXRhciI6ImFlZTY2OGYxLTYxMWYtNGVlMy1iNThlLTQ5MjVmMzYzNjgyOCIsImVtYWlsIjoiZ2xpbWFAZ21haWwuY29tIiwiaWF0IjoxNzA1NjEyMjk3LCJleHAiOjE3MDU2NDEwOTd9.OHZ4LQoEPMTYPKjMXs-TlZMyyxWJin5BazknfFWjjG0

{
    "usernameFollowing":"bianca"
}